apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomad.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-app
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-app
    app.kubernetes.io/instance: {{ .Release.Name }}
